from contextlib import AbstractAsyncContextManager, AbstractContextManager
from typing import Any, List, Optional
from agent_honesty.interceptors.tool_decorator import (
    ToolExecutionRecord,
    _ACTIVE_AUDIT_LOG,
)

class HonestyAuditor(AbstractContextManager, AbstractAsyncContextManager):
    """
    Context manager for capturing execution records generated by @audit_tool decorators.

    Example:
        with HonestyAuditor() as auditor:
            result = my_tool(x=10)
            print(auditor.records)
    """
    def __init__(self) -> None:
        self.records: List[ToolExecutionRecord] = []
        self._token: Optional[Any] = None

    def __enter__(self) -> "HonestyAuditor":
        self._token = _ACTIVE_AUDIT_LOG.set(self.records)
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        if self._token is not None:
            _ACTIVE_AUDIT_LOG.reset(self._token)
            self._token = None

    async def __aenter__(self) -> "HonestyAuditor":
        return self.__enter__()

    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        self.__exit__(exc_type, exc_val, exc_tb)
